import type { Metadata } from "next";
import { Geist, Geist_Mono, Metrophobic } from "next/font/google";
import "./globals.css";

const metrophobic = Metrophobic({
  weight: "400", // or other weights if available
  subsets: ["latin"],
  display: "swap",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" bbai-tooltip-injected="true">
      <body className={`${metrophobic.className} antialiased`}>{children}</body>
    </html>
  );
}
